# Generated by Django 3.2.13 on 2022-07-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('fiyat', models.BigIntegerField()),
                ('stok', models.BigIntegerField()),
                ('kategorim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anasayfa.kategori')),
            ],
        ),
    ]
