# Generated by Django 3.2.13 on 2022-07-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0002_urunler'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='urun_resim',
            field=models.FileField(blank=True, null=True, upload_to='urun_resim/'),
        ),
    ]
